<div class="top-content-home">
	<div class="banner-top-home">
		<div class="container-fluid">
			<?php echo $block->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("PWF_Content::home_promo_a.phtml")->toHtml();?>
		</div>
	</div>
	<div class="banner-top-home">
		<div class="container">
			<?php echo $block->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("PWF_Content::home_videos.phtml")->toHtml();?>
		</div>
	</div>
	<div class="box-new">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_left_new')->toHtml();?>
				</div>
				<div class="col-md-6 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?> 
				</div>
			</div>
		</div>
	</div>
	<div class="box-new">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct')->setTemplate('Magento_Catalog::product/category_mostviewed.phtml')->setCategoryId(54)->toHtml();?>
				</div>
			</div>
		</div>
	</div>

	<div class="onsale-home">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?> 
		</div>
	</div>
	<div class="box-banner-middle">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle')->toHtml();?>
		</div>
	</div>
	<div class="group-product">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct')->setTemplate('Magento_Catalog::product/category_bestseller.phtml')->setCategoryId(53)->toHtml();?>
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Featuredpro\Block\Featured')->setTemplate('Rokanthemes_Featuredpro::featured.phtml')->toHtml();?> 
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct')->setTemplate('Magento_Catalog::product/category_mostviewed.phtml')->setCategoryId(54)->toHtml();?>
				</div>
			</div>
		</div>
	</div>
	
</div>