<div class="footer-container">
	<div class="footer-top">
		<div class="container">
			<?php echo $this->getChildHtml("footer_shipping"); ?>
		</div>
	</div>
	<div class="footer-static-container">
		<div class="container">
			<?php echo $this->getChildHtml("footer_static"); ?>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<?php echo $this->getChildHtml("footer_links"); ?>
				</div>
				<div class="col-md-6 col-xs-12">
					<?php echo $this->getChildHtml("copyright"); ?>
				</div>
			</div>
			<div id="back-top" class="hidden-xs"><i class="fa fa-long-arrow-up"></i></div> 
		</div>
	</div>
</div>