<div class="header-container">
	<div class="top-link-container">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 top-bar">
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("social_header"); ?>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 end-top-bar">
					<?php echo $this->getChildHtml("top.search"); ?>
					 <?php echo $this->getChildHtml("minicart");?>
					 <?php echo $this->getChildHtml("register_login"); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="header">
		<div class="container">
			<?php echo $this->getChildHtml("logo"); ?>
		</div>
	</div>
	<div class="top-menu">
		<div class="container">
			<?php echo $this->getChildHtml("top.navigation.sections"); ?>	
		</div>
	</div>
</div>

