<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.s
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
    $_product = $block->getProduct();
    $tour_code = $_product->getData('tour_code'); 
    $isCruise = $_product->getAttributeSetId() == '10';
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
	<?php if($isCruise) : ?>
		<?php 
		  $has_meals = $_product->getData('has_meals') == '1';
		  $controller_name = ($has_meals) ? 'mealsAndTickets' : '';
        ?>
        <div class="box-tocart" ng-app="ticketSelectorApp">
            <div class="fieldset" ng-controller="timeAndDate">
                <?php if ($block->shouldRenderQuantity()): ?>
                <input type="hidden" name="is_cruise" value="1"/>
                <h2>Select Date and Time:</h2>
                <div class="row cruise-date-time-controls">
                	<div class="col-md-3">
                        <div class="field">
                            <label class="label" for="cruise_date"><span><?php /* @escapeNotVerified */ echo __('Cruise Date') ?></span></label>
                            <div class="control">
                                <!--  <input type="text" name="cruise_date" id="cruise_date" value="10/1/2016" style="width:100px"><br/> -->
                                <input ng-model="cruiseDate" class="datepicker" name="cruise_date" id="cruise_date" required class="form-control" type="text" id="pdp-date" />
                            </div>
                        </div>	
                	</div>
                	<div class="col-md-9">
                        <div class="field">
                            <label class="label" for="cruise_time"><span><?php /* @escapeNotVerified */ echo __('Cruise Time') ?></span></label>
                            <div class="control">
                                <select name="cruise_time" id="cruise_time" ng-disabled="hasNoTimes()" ng-options="cruiseTime.time for cruiseTime in cruiseTimes track by cruiseTime.time" ng-model="cruiseTime" style="width:100px"></select>
                            </div>
                        </div>
                	</div>
                </div>
        
        	</div>
        	<div class="fieldset" ng-controller="<?php echo $controller_name; ?>">
                <div>
                    <div class="control cruise-tickets">
                    	<h2>Choose Tickets:</h2>
        				<?php 
        				    $related_products = $_product->getRelatedProductIds(); 
        				    $object_manager = \Magento\Framework\App\ObjectManager::getInstance();
        				    $sorted_related_products = [];
            				foreach($related_products as $pid){
            					$related_product = $object_manager->create('Magento\Catalog\Model\Product')->load($pid);
            					$age_limit = $related_product->getData('age_limit');
            					$sorted_related_products[$age_limit] = $related_product;
            				}
            				$result = krsort($sorted_related_products);				
        				?>
        				<input type="hidden" name="parent_id" value="<?php echo $_product->getId(); ?>"/>
                        <?php foreach($sorted_related_products as $sorted_related_product): ?>
                            <?php 
                                $product_id = $sorted_related_product->getId();
                                $product_name = $sorted_related_product->getName();
                                $product_price = $sorted_related_product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                            ?>
        					<input type="hidden" name="ticket_id[]" value="<?php echo $product_id; ?>"/>
                            <div class="cruise-ticket">
                            	<label class="label cruise-ticket-label" for="">
                            		<span>
                            			<?php echo $product_name?> : $<?php echo $product_price?>
                            		</span>
                            	</label>
                            	<input type="text" ng-change="getTotalMeals()" ng-model="tickets._<?php echo $product_id; ?>" name="ticket_qty[]" value="0" style="width:40px"/>
                            </div>
        				<?php endforeach; ?>	
                    </div>
                </div>
                
                <?php if($has_meals) : ?>
                <div>
                	<div class="control cruise-meals">
                		<h2>Choose Meals</h2>
                		<h4>{{getMessage()}}</h4>
                        <div class="cruise-ticket">
                        	<label class="label cruise-ticket-label" for="">
                        		<span>
                        			Steak :
                        		</span>
                        	</label>
                        	<input type="hidden" name="meal_id[]" value="0" style="width:40px" value="99"/>
                        	<input type="text" name="meal_qty[]" value="0" style="width:40px" ng-change="getTotalMeals()" ng-model="steak"/>
                        </div>
                        <div class="cruise-ticket">
                        	<label class="label cruise-ticket-label" for="">
                        		<span>
                        			Shrimp :
                        		</span>
                        	</label>
                        	<input type="hidden" name="meal_id[]" value="0" style="width:40px" value="99"/>
                        	<input type="text" name="meal_qty[]" value="0" style="width:40px" ng-change="getTotalMeals()" ng-model="shrimp"/>
                        </div>
                        <div class="cruise-ticket">
                        	<label class="label cruise-ticket-label" for="">
                        		<span>
                        			Chicken :
                        		</span>
                        	</label>
                        	<input type="hidden" name="meal_id[]" value="0" style="width:40px" value="99"/>
                        	<input type="text" name="meal_qty[]" value="0" style="width:40px" ng-change="getTotalMeals()" ng-model="chicken"/>
                        </div>
                        <div class="cruise-ticket">
                        	<label class="label cruise-ticket-label" for="">
                        		<span>
                        			Vegetarian :
                        		</span>
                        	</label>
                        	<input type="hidden" name="meal_id[]" value="0" style="width:40px" value="99"/>
                        	<input type="text" name="meal_qty[]" value="0" style="width:40px" ng-change="getTotalMeals()" ng-model="vegetarian"/>
                        </div>
                	</div>
                </div>
                <?php endif;?>
                
                
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
	<?php else : ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qantity :') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qantity') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                    </div>
                </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>

	<?php endif; ?>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js"></script>

<script>
<?php if($isCruise) : ?>
	var _$;
	Date.prototype.mmddyyyy = function() {
		  var mm = this.getMonth() + 1; // getMonth() is zero-based
		  if(mm < 10){mm = "0" + mm}
		  var dd = this.getDate();
		  if(dd < 10){dd = "0" + dd}
		  return [mm, dd, this.getFullYear()].join('/'); // padding
		};
<?php endif; ?>
		
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';
        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
        <?php if($isCruise) : ?>
		_$ = $;
        $('body').addClass("category-cruises");

        var tour_code = $('#tour_code').val();
        <?php endif; ?>
    });
    <?php if($isCruise) : ?>    
    var t = angular.module('ticketSelectorApp',[]);

    // meals controller
    t.controller('mealsAndTickets', function($scope){
        $scope.totalMeals = 0;
        $scope.totalTickets = 0;
        $scope.steak = 0;
        $scope.shrimp = 0;
        $scope.chicken = 0;
        $scope.vegetarian = 0;
        $scope.tickets = {};
        $scope.getNumericValue = function(n){
            var i = parseInt(n);
            return (!isNaN(i)) ? i : 0;
        }
		$scope.getTotalMeals = function(){
			$scope.totalMeals = $scope.getNumericValue($scope.steak) + $scope.getNumericValue($scope.shrimp) + $scope.getNumericValue($scope.chicken) + $scope.getNumericValue($scope.vegetarian);
			$scope.totalTickets = $scope.getTotalTickets();
		}
		$scope.getTotalTickets = function(){
			var qInputs = _$('.cruise-tickets .cruise-ticket input');
			var len = qInputs.length;
			var total = 0;
			for(var i = 0; i < len; i++){
				total += $scope.getNumericValue(_$(qInputs[i]).val());
			}
			return total;
		}
		$scope.getMessage = function(){
			return("Total Meals: " + $scope.totalMeals + "  -  Total Tickets: " + $scope.totalTickets);
		}
        
    });

    // controller
    t.controller('timeAndDate',function($scope,$http){
        $scope.datesAndTimes = [];
        $scope.cruiseTime = "loading";
        $scope.cruiseTimes = [];
        $scope.cruiseDate = 'Loading Dates...';
        $scope.tourCode = 0;
        loadDatesAndTimes($scope);
        var datesAndTimes;
        function hasNoTimes(){
			var b = ($scope.cruiseTimes.length == 0);
			return b;
        }
        $scope.hasNoTimes = hasNoTimes;
        function loadDatesAndTimes($scope){
        	$scope.tourCode = '<?php echo $tour_code;?>';
        	$http.post('/m/custom/check_avail.php', {tourcode:$scope.tourCode}).then(function(response){
        		$scope.datesAndTimes = response.data;
        		$scope.cruiseDate = 'Select a date';
				var options = {
					autoClose: true,
		            dateFormat: 'mm-dd-yy',
		            constrainInput: false,
		            minDate: new Date(),
		            onSelect: function(dt, dp){
		                return onDaySelect(dt, $scope)
		            },
		            beforeShowDay: function(dt){
		                return checkDayForCruises(dt, $scope);
		            }
				}
				$scope.daypicker = _$('.datepicker').datepicker(options);
        	});
          }
        function checkDayForCruises(dt, $scope){
			var hasCruise = !($scope.datesAndTimes[dt.mmddyyyy()] === undefined);
			var dd = new Date()
			if(dd.mmddyyyy() == dt.mmddyyyy()){
				hasCruise = true;
			}
			return [hasCruise, 'highlight'];
        }
        function onDaySelect(dt, $scope){
            dt = new Date(dt);
			$scope.cruiseTimes = $scope.datesAndTimes[dt.mmddyyyy()];
			$scope.cruiseTime = $scope.cruiseTimes[0].time;
			$scope.$digest();
        }
      });
<?php endif; ?>





    
</script>
<?php endif; ?>