<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.s
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        
        <input type="hidden" name="is_cruise" value="1"/>
        <h2>Select Date and Time:</h2>
        <div class="row cruise-date-time-controls">
        	<div class="col-md-3">
                <div class="field">
                    <label class="label" for="cruise_date"><span><?php /* @escapeNotVerified */ echo __('Cruise Date') ?></span></label>
                    <div class="control">
                        <input type="text" name="cruise_date" id="cruise_date" value="10/1/2016" style="width:100px"><br/>
                    </div>
                </div>	
        	</div>
        	<div class="col-md-9">
                <div class="field">
                    <label class="label" for="cruise_time"><span><?php /* @escapeNotVerified */ echo __('Cruise Time') ?></span></label>
                    <div class="control">
                        <input type="text" name="cruise_time" id="cruise_time" value="7:00am" style="width:100px"><br/>
                    </div>
                </div>
        	</div>
        </div>


        <div>
            <div class="control cruise-tickets">
            	<h2>Choose Tickets:</h2>
				<?php 
				    $related_products = $_product->getRelatedProductIds(); 
				    $object_manager = \Magento\Framework\App\ObjectManager::getInstance();
				    $sorted_related_products = [];
    				foreach($related_products as $pid){
    					$related_product = $object_manager->create('Magento\Catalog\Model\Product')->load($pid);
    					$age_limit = $related_product->getData('age_limit');
    					$sorted_related_products[$age_limit] = $related_product;
    				}
    				$result = krsort($sorted_related_products);
    				$x=9;				
				?>
				
                <?php foreach($sorted_related_products as $sorted_related_product): ?>
                    <?php 
                        $product_id = $sorted_related_product->getId();
                        $product_name = $sorted_related_product->getName();
                        $product_price = $sorted_related_product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                    ?>
					<input type="hidden" name="ticket_id[]" value="<?php echo $product_id; ?>"/>
                    <div class="cruise-ticket">
                    	<label class="label cruise-ticket-label" for="">
                    		<span>
                    			<?php echo $product_name?> : $<?php echo $product_price?>
                    		</span>
                    	</label>
                    	<input type="text" name="ticket_qty[]" value="0" style="width:40px"/>
                    </div>
				<?php endforeach; ?>
				
				
				   	
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });

        $('body').addClass("category-cruises");
    });
</script>
<?php endif; ?>