<?php
   /**
    * Copyright © 2015 Magento. All rights reserved.
    * See COPYING.txt for license details.
    */
   
   // @codingStandardsIgnoreFile
   
   /* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
   ?>
<?php
   switch ($type = $block->getType()) {
   
   
   
		case 'upsell':
			/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
			if ($exist = count($block->getItemCollection()->getItems())) {
				$type = 'upsell';
				$class = $type;

				$image = 'upsell_products_list';
				$title = __('upsell products');
				$items = $block->getItemCollection()->getItems();
				$limit = $block->getItemLimit('upsell');
				$shuffle = 0;

				$showWishlist = true;
				$showCompare = true;
				$showCart = true;
				$templateType = null;
				$description = false;
				$canItemsAddToCart = false;
			}
			break;
   
       case 'other':
       break;
   }
   ?>
<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'upsell'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
   <div class="container">
	<div class="rokan-product-heading rokan-upsell-heading">
      <h2><span><?php echo $title; ?></span></h2>
	</div>
    
	<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading"> 
	   <div class="row">
			<div id="upsell_product_slider" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>  
				<?php
					$productImage = $block->getImage($_item, $image);
					
					
				?>
					<?php if ($i++%$rows==0) { ?>
					<div class="products-item">
						<?php } ?>
						<div class="product-item">
							<div class="product-photo">
								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
								<div class="quickview-product">
									<a  data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i><?php echo ('Quick view') ?></i></a>
								  </div>
							</div>
							<div class="product-info">
								<div class="pull-left">
									<h3 class="product-name">
										<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?></a>
									</h3>
									<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
									<?php echo $block->getProductPrice($_item); ?>									
								</div>
								<div class="addto-links-icons visible-onhover pull-right">
										<div class="action-inner">
											<div class="actions-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
													<?php else: ?>
													<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												   $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												   ?>
													<button class="btn btn-add-to-cart"
													   data-post='<?php echo $postData; ?>'
													   type="button" title="<?php echo __('Add to Cart') ?>">
														<i class="fa fa-shopping-basket">&nbsp;</i>
													</button>
													<?php endif; ?>
													<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php echo __('In stock') ?></span></div>
													<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
												<!--<?php if ($showWishlist || $showCompare): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<a href="#" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to WishList') ?>">
													<span><?php echo __('WishList') ?></span>
													</a>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php
													   $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													   ?>
													<a href="#" class="action tocompare"
													   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
													   data-role="add-to-links"
													   title="<?php echo __('Add to Compare'); ?>">
													<span><?php echo __('Compare') ?></span>
													</a>
													<?php endif; ?>

												<?php endif; ?>-->
											</div>
										</div>
									</div>
							</div>
		
						</div>
						<?php if($i%$rows==0 || $i == count($items)) { ?> 
					</div> 
					<?php } ?>
				<?php endforeach ?>
			</div>
		</div> 
    </div> 
    </div> 
</section>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#upsell_product_slider").owlCarousel({
			autoPlay : false,
			items : 4,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [980,2],
			itemsTablet: [768,2],
			itemsMobile : [479,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
</script>
