<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
$orig_items = $block->getItems();
$cart_helper =  $this->helper('PWF\Cart\Helper\Data');
$cruises =      $cart_helper->getCruiseTickets($block->getItems());
$non_cruises =  $cart_helper->getNonCruiseItems($block->getItems());
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>



<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Item') ?></span></th>
                    <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                    <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                </tr>
            </thead>
            <?php foreach ($cruises as $item): ?>
            	<tr>
            		<td colspan="4">
                		<div class="product-item-details">
                    		<strong class="product-item-name">Tickets : <?php echo $item['cruise_product']['name']?></strong>
                            <dl class="item-options">
                            	<dt>Date</dt>
                                <dd><?php echo $item['cruise_product']['date']?></dd>
                                <dt>Time</dt>
                                <dd><?php echo $item['cruise_product']['time']?></dd>
							</dl>
							<?php if(count($item['cruise_meals']) > 0) : ?>
    							<dl class="item-options">
    								<?php foreach($item['cruise_meals'] as $meal) : ?>
    									<dt><?php echo $meal['name']?></dt><dd><?php echo $meal['qty']?></dd>
    								<?php endforeach?>
    							</dl>
							<?php endif;?>
                        </div>
            		</td>
            	</tr>
            	<?php foreach ($item['cruise_tickets'] as $ticket):?>
                	<tr>
                		<td style="padding-left:50px">
                    		<div class="product-item-details">
                        		<strong class="product-item-name"><?php echo $ticket['name']?></strong>
                            </div>
                		</td>
                		<td><?php echo $ticket['price']?></td>
                		<td><?php echo $ticket['qty']?></td>
                		<td><?php echo $ticket['subtotal']?></td>
                	</tr>
            	<? endforeach;?>
            	<tr class="item-actions">
                    <td colspan="100">
                        <div class="actions-toolbar">
                                <a class="action action-delete" href="http://localhost:8888/m/checkout/cart/deletecruise/id/<?php echo $item['cruise_product']['cart_id']?>" title="Delete Cruise Tickets"><span>Remove this cruise </span></a>
                        </div>
                    </td>
                </tr>
            <? endforeach;?>
            
            
            <?php foreach ($non_cruises as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
                <!-- 
                    need a list of cruises with tickets as subs
                    modify cart block to get

                -->
            <?php endforeach ?>
        </table>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

