
<div class="row">
	<div class="col-md-6 col-sm-6 col-xs-12 col-banner-top">
		<h2>Molokini</h2>
		<div class="embed-responsive embed-responsive-16by9">
		  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/SvihOHFC0II" allowfullscreen></iframe>
		</div>
		
	</div>
	<div class="col-md-6 col-sm-6 col-xs-12 col-banner-top">
		<h2>Whalewatch</h2>
		<div class="embed-responsive embed-responsive-16by9">
		  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/eFBQ0jH_Zq8" allowfullscreen></iframe>
		</div>
	</div>
</div>