

<?php 
//$object_manager = Magento\Core\Model\ObjectManager::getInstance();
// $dir = $object_manager->get('Magento\App\Dir');            
// $base = $dir->getUrl(Magento\App\Dir::MEDIA);
?>

<div class="row">
	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
	<div class="banner-top banner-top1">
	<div class="bs-banner"><a href="#"><img src="<?php echo '/m/pub/media/'. 'homepagemedia/promo_a_1.png';?>" alt="" /></a>
	<div class="bs-banner-text">
	<h3>Choose Your Adventures</h3>
	<p>amet consectetur adipiscing elit.</p>
	<a class="view-collection">Find the right one for you</a></div>
	</div>
	</div>
	</div>
	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
	<div class="banner-top banner-top2">
	<div class="bs-banner"><a href="#"><img src="<?php echo '/m/pub/media/'. 'homepagemedia/promo_a_1.png';?>" alt="" /></a>
	<div class="bs-banner-text">
	<h3>Experience the PWF Difference</h3>
	<p>We have the most boats and the most cruises on Maui.</p>
	<a class="view-collection">Learn More</a></div>
	</div>
	</div>
	</div>
	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
	<div class="banner-top banner-top3">
	<div class="bs-banner"><a href="#"><img src="<?php echo '/m/pub/media/'. 'homepagemedia/promo_a_1.png';?>" alt="" /></a>
	<div class="bs-banner-text">
	<h3>Desinations</h3>
	<p>amet consectetur adipiscing elit.</p>
	<a class="view-collection" href="destinations">Where do you want to go?</a></div>
	</div>
	</div>
	</div>
</div>

