

<?php 
//$object_manager = Magento\Core\Model\ObjectManager::getInstance();
// $dir = $object_manager->get('Magento\App\Dir');            
// $base = $dir->getUrl(Magento\App\Dir::MEDIA);
?>

<div class="row">
	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
		<div class="banner-top banner-top1">
			<a href="adventure.html">
				<img src="<?php echo '/m/pub/media/'. 'homepagemedia/sample/Choose_Your_Adventure1.jpg';?>" alt="" />
			</a>
			<a href="#">
				<img src="<?php echo '/m/pub/media/'. 'homepagemedia/sample/Choose_Your_Destination1.jpg';?>" alt="" />
			</a>
		</div>
	</div>

	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
		<div class="banner-top banner-top2">
			<a href="#">
				<img src="<?php echo '/m/pub/media/'. 'homepagemedia/sample/Video_02_duo.jpg';?>" alt="" />
			</a>
		</div>
	</div>

	<div class="col-md-4 col-sm-4 col-xs-12 col-banner-top">
			<div class="banner-top banner-top3 pwf-hover-block">
					<div class="pwf-banner-text">
						<h3>The PWF Difference</h3>
						<p>Lorem ipsum dolor consequet Lorem ipsum dolor consequet Lorem ipsum dolor consequet ...</p>
					</div>
				<div class='pwf-banner'>
					<a href="#"><img src="<?php echo '/m/pub/media/'. 'homepagemedia/sample/PWF_diff_01_duo.jpg';?>" alt="" /></a>
				

				</div>
			</div>
		</div>
	</div>
</div>

